### ISSUE TITLE
with_ros2bagで地図作成ができない

### ISSUE THREAD

**Issue by shunsugar** [KBKN-Autonomous-Robotics-Lab/orange_ros2#100]
## 概要
bagファイルに必要な**トピックが揃っている**にも関わらず、

- `ros2 launch orange_bringup with_ros2bag.launch.xml`
- `ros2 launch orange_slam slam_toolbox.launch.xml with_ros2bag:=true`
- `ros2 bag play {BAG_FILE_NAME}`

の3つを起動しても地図が作成できません。

**frame**や**use_sim_timeの問題**だと思っています。おそらくodomとlivox_frameのフレームが繋がっていないのが原因です。
今、作業しているブランチは[fix/with_ros2bag](https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2/tree/fix/with_ros2bag)です。これは最優先に解決したいです。お願いします。

## odom
Odometry形式のトピックである`/odom`や`/odom_fast`、`/odom_CLAS_movingbase`、`/fusion/odom`の確認はできています。

![スクリーンショット 2024-10-29 160029](https://github.com/user-attachments/assets/bf103478-f446-44ae-8e2b-757c1d3efd7a)

## livox_frame
/livox/lidarをpointcloud2形式に変換したトピックもそれぞれ確認できています。

![スクリーンショット 2024-10-29 160102](https://github.com/user-attachments/assets/df6e0533-e120-42d8-8d85-2f1367e1b4d1)

**Comment by kugurofu** [comment]
解決したため、以下に解決までに行ったことを示します。
・ros2 launch orange_bringup with_ros2bag.launch.xml のnodeすべてにuse_sim_time=trueを設定
・rosbagのplay時にオプションとして--clockを設定
この二つを行うことで解決しました。

プログラム内でuse_sim_timeの設定がない場合でもlaunchに追記することで解決できます。
以下に記述例を示します。

## launch.xmlの場合
#### launchを実行している場合はargを使用します。
 
`<include file="$(find-pkg-share your_package)/launch/your_launch.launch.xml">`
> 

    <arg name="use_sim_time" value="true"/>

#### nodeを実行している場合はparamを使用します。
  `<node pkg="your_package" exec="your_node">`

> 

    <param name="use_sim_time" value="true"/>

## launch.pyの場合
まだ確認できていませんが、おそらくparametersを使用します。

> 

            parameters=[{
                'use_sim_time': True
            }],

## コマンド
今後rosbagを使用してmapを作成する際のコマンドを示しておきます。
・`ros2 launch orange_bringup with_ros2bag.launch.xml use_sim_time:=true`
・`ros2 launch orange_slam slam_toolbox.launch.xml use_sim_time:=true with_ros2bag:=true`
・`ros2 bag play {BAG_FILE_NAME} --clock`

**Comment by shunsugar** [comment]
参考として過去のissueとpull requestを上げておきます。

- #51 
- #53
