### ISSUE TITLE
Navigation2のパラメータ調整

### ISSUE THREAD

**Issue by Alpaca-zip** [KBKN-Autonomous-Robotics-Lab/orange_ros2#13]
Navigation2実行時に遭遇した問題は以下の通りです。
- 稀に、local costmapが表示されないことがある。
- WSLではnavigation2実行後にCtrl+cでkillしないことがある。
- 実行時はとにかく重い。gazeboのReal Time Factorが0.1を切ることも時々。
- Plannerに[DWB Controller](https://github.com/ros-planning/navigation2/tree/main/nav2_dwb_controller)のみを利用する場合には問題ないが、[Rotation Shim Controller](https://github.com/ros-planning/navigation2/tree/main/nav2_rotation_shim_controller)と併用するとControl loopが頻繁にミスする。
https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2/blob/777922dc974b3540a58de466a12ad4bfceec736a/orange_navigation/config/navigation2_params.yaml#L131-L132

これらは必要に応じてissueを立てて対応していこうと思います。その他、新たに問題を発見した場合には追記していただけるとありがたいです。

**Comment by Alpaca-zip** [comment]
Navigation2のデフォルトのパラメータは以下にあります。
https://github.com/ros-planning/navigation2/blob/main/nav2_bringup/params/nav2_params.yaml

**Comment by shunki1006** [comment]
参考になりそうなリンクなのでここに残しておきます. 
https://navigation.ros.org/tuning/index.html#nav2-launch-options
https://nutritionfoodtech.com/2022/12/04/slam%E3%81%A7%E4%BD%9C%E6%88%90%E3%81%97%E3%81%9Fmap%E3%81%A7navigation2-%E8%A8%AD%E5%AE%9A%E7%A2%BA%E8%AA%8D%E7%B7%A8-ros2-foxy/#toc5

**Comment by shunki1006** [comment]
amclのパラメータはfix_amcl_param(2f6909789c3501b56b9ac0a20d2ccf2a7193295e)のcommitで一旦完了にします. 
現状costmapが原因だと考えているので, ここからcostmapの部分を詰めていきます.

**Comment by Alpaca-zip** [comment]
DWBコントローラーのパラメータの簡単な説明はここにあります。
https://navigation.ros.org/configuration/packages/dwb-params/controller.html

**Comment by shunki1006** [comment]
> DWBコントローラーのパラメータの簡単な説明はここにあります。 https://navigation.ros.org/configuration/packages/dwb-params/controller.html

https://navigation.ros.org/configuration/packages/configuring-dwb-controller.html

**Comment by Alpaca-zip** [comment]
ROS1のNavigation Stackのパラメータ調整をする際には以下のサイトをよく参考にしていました。
https://sy-base.com/myrobotics/ros/ros-move_base/

似た名前のパラメータもあると思うのでROS2においても参考になるかと思います。

**Comment by shunki1006** [comment]
costmap, DWBコントローラーを調整し, つくばチャレンジ確認走行をクリアしたパラメータはblank_line_delete_&_speed_adj(101b2d0a549e38dd88eb87a5521f2b902719321e)のコミットを参考にしてください.

**Comment by shunki1006** [comment]
速度が遅すぎる問題があるので, 次はそちらに対応していく予定です.

**Comment by shunki1006** [comment]
速度関係のパラメータを以下のように設定すると, 自己位置に問題が発生するのでまた別のブランチを切って対応します. 
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 1.0
      max_vel_y: 0.0
      max_vel_theta: 1.0
      min_speed_xy: 0.0
      max_speed_xy: 1.0
      min_speed_theta: 0.0
      acc_lim_x: 0.5
      acc_lim_y: 0.0
      acc_lim_theta: 1.0
      decel_lim_x: -0.5
      decel_lim_y: 0.0
      decel_lim_theta: -1.0

velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [1.0, 0.0, 1.0]
    min_velocity: [-1.0, 0.0, -1.0]
    max_accel: [0.5, 0.0, 1.0]
    max_decel: [-0.5, 0.0, -1.0]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0

**Comment by shunki1006** [comment]
速度が遅い問題と, それに付随する自己位置が吹き飛ぶ問題はfix_amcl_&_DWB_velocity_param(dc584c3726b9425d2b1fd65b11ca83991126e9e7)のコミットで一旦終了します. 
速度が上がったことによる障害物回避が間に合うのか問題はfix/nav2_local_costmapで対応しています.

**Comment by shunki1006** [comment]
@Alpaca-zip Nav2パラメータ調整に関しては以下のIssueにあげている方向合わせに時間がかかること以外は修正しつくばチャレンジの本走行を終えたので, 本Issueは閉じて, 方向合わせの問題は以下のIssue内で対応しようと思うのですがいかがでしょうか？
https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2/issues/74#issue-1977032068

**Comment by Alpaca-zip** [comment]
> @Alpaca-zip Nav2パラメータ調整に関しては以下のIssueにあげている方向合わせに時間がかかること以外は修正しつくばチャレンジの本走行を終えたので, 本Issueは閉じて, 方向合わせの問題は以下のIssue内で対応しようと思うのですがいかがでしょうか？ [#74 (comment)](https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2/issues/74#issue-1977032068)

良いと思います。よろしくお願いします。
