### ISSUE TITLE
[wstool] .rosinstallへのgithubリポジトリの追加

### ISSUE THREAD

**Issue by Alpaca-zip** [KBKN-Autonomous-Robotics-Lab/orange_ros2#27]
https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2/pull/26 のPRにて[velodyne](https://github.com/ros-drivers/velodyne)を`.rosinstall`に追加しましたが、以下のROS2パッケージについても利用頻度が高いため、wstoolで`git clone`してソースコードが見れた方が良いと思います。
- navigation2: https://github.com/ros-planning/navigation2
- robot_localization: https://github.com/cra-ros-pkg/robot_localization
- pointcloud_to_laserscan: https://github.com/ros-perception/pointcloud_to_laserscan
- cartographer: https://github.com/cartographer-project/cartographer_ros
- slam_toolbox: https://github.com/SteveMacenski/slam_toolbox

**Comment by shunki1006** [comment]
本Issueの対応をしたのですがメモリ不足によりbuildが通らなくなってしまったため, closeします.

**Comment by shunki1006** [comment]
本Issueの対応をしたのですがメモリ不足によりbuildが通らなくなってしまったため, closeします.
