### ISSUE TITLE
[orange_bringup] motor_driver_nodeが落ちる

### ISSUE THREAD

**Issue by Alpaca-zip** [KBKN-Autonomous-Robotics-Lab/orange_ros2#50]
`teleop_keyboard.launch.xml`を実行してキーボードでロボットを操作中に、motor_driver_nodeが落ちる現象が発生しました。
スペースキーを押してロボットを停止させる際に当該問題に出くわしましたが因果関係は不明です。

現在、原因究明中です。

**Comment by shunki1006** [comment]
モータードライバの接合部分が経年劣化により外れかけているというハードウェアの問題がありました. 
接合部分を新しくしたことによりハードウェアの問題を解決したことにより,ついでにこのIssueも解決されると思います.
