### ISSUE TITLE
ros2bagでの走行ができない件について

### ISSUE THREAD

**Issue by shunki1006** [KBKN-Autonomous-Robotics-Lab/orange_ros2#51]
ros2bag_orange_hosei①ではできるが, rosbag2_2023_07_12-09_56_11②ではできない. 
それぞれのtopicは以下の通り. 
①/tf, /velodyne_scan, /merged_scan, /imu, /hokuyo_scan, /fusion/odom
②/hokuyo_scan, /velodyne_points, /imu, /odom

現在原因解明中. 今後明らかになったこともこのissueに随時あげていきます.

**Comment by Alpaca-zip** [comment]
bagファイルを再生しているとしばらく地図が作成されないのは、2023/07/12での走行で取得したbagファイル(rosbag2_2023_07_12-09_56_11②)の`/velodyne_points`トピックが一部欠落しているためだと思います。

**Comment by Alpaca-zip** [comment]
左右のタイヤのTFが発行されていない問題は、robot_state_publisherが左右のタイヤ`の/joint_state`を購読できていないことが原因のようです。シミュレーション環境ではgazeboが直接robot_state_publisherに対して`/joint_state`を投げますが、実機環境ではこれを投げるノードが存在しません。

これを回避するために、IGVC2023-srcでは以下の箇所でjoint_state_publisherを追加しています。
https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/blob/f6ee81bedf2fa0aba68b30d3c4ebb4fe56b9571e/igvc2023/launch/sensors.launch#L23-L26

joint_state_publisherを追加すると、rviz2で正しい位置にタイヤが表示されます。

<img src="https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2/assets/84959376/a7ca065c-1f3d-4afd-b4b2-bcd088e79ab3" width="500">

**Comment by Alpaca-zip** [comment]
作業ブランチは以下です。
[feature/launch_for_ros2bag](https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2/tree/feature/launch_for_ros2bag)

基本的に、`/hokuyo_scan`, `/velodyne_points`, `/imu`, `/odom`を欠落することなく用意し、`/fusion/odom`と`/merged_scan`を正しく生成できていればslam_toolboxで地図作成はできると思います。今の所気になるのは、以下のように`/odom`(赤)と`/fusion/odom`(黄)に大きなずれがあることです。

<img src="https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2/assets/84959376/6b3f67a7-0885-4e54-af6e-884653685dc9" width="800">

これはrobot_localizationのパラメータの問題だと思うので別issueで対応した方がよさそうです。

**Comment by Alpaca-zip** [comment]
また、`orange_robot.launch.xml`でmotor_driver_nodeの`publish_TF`を`true`にしているのも気になります。
https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2/blob/79b6c5dbee773e4c2a4a1cb1123b6d06f79d4f9a/orange_bringup/launch/orange_robot.launch.xml#L12
これだと、robot_localizationが発行するTFと競合が発生してしまう気がします。

**Comment by Alpaca-zip** [comment]
> この画像はorange_ros2内のものなのか, IGVC2023-srcのものなのかどちらでしょうか？
仮にorange_ros2のものならばpush済みの内容ですか？

orange_ros2のものです。
[feature/launch_for_ros2bag](https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2/tree/feature/launch_for_ros2bag)ブランチのhttps://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2/commit/4c04e888b2154876bd30625c88eebcdf029b72ee で既に反映済みです。

**Comment by shunki1006** [comment]
> > この画像はorange_ros2内のものなのか, IGVC2023-srcのものなのかどちらでしょうか？
> > 仮にorange_ros2のものならばpush済みの内容ですか？
> 
> orange_ros2のものです。 [feature/launch_for_ros2bag](https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2/tree/feature/launch_for_ros2bag)ブランチの[4c04e88](https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2/commit/4c04e888b2154876bd30625c88eebcdf029b72ee) で既に反映済みです。

承知です、ありがとうございます。

**Comment by shunki1006** [comment]
bagファイルを取り直し, ros2 bag playで動かしましたが, /odomと/fusion/odomが変わらず一致していませんでした. 
これが原因で地図の作成ができていないと思われるのでrobot_localizationの方のissueの対応に先にあたろうと思います.
