### ISSUE TITLE
ホイールオドメトリのみでのナビゲーション走行

### ISSUE THREAD

**Issue by shunki1006** [KBKN-Autonomous-Robotics-Lab/orange_ros2#54]
現状の問題
・/odomと/fusion/odomが一致せず, /fusion/odomがスタート地点から動かない. 
<img src="https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2/assets/88425011/c2986cb9-32ce-4ffd-a9eb-846d3f151b30" width="500px"> 

本Issueでの対応
・IMUの情報を利用せずにホイールオドメトリのみでの地図作成及びナビゲーション走行を行う

**Comment by shunki1006** [comment]
@Alpaca-zip このIssue用のブランチ切ってそこでホイールオドメトリのみでの走行を行おうと思うのですが問題ないですか？
完成した場合, ホイールオドメトリのみの場合とIMUありの場合の取り扱いについては本日決めましょう.

**Comment by Alpaca-zip** [comment]
> @Alpaca-zip このIssue用のブランチ切ってそこでホイールオドメトリのみでの走行を行おうと思うのですが問題ないですか？
完成した場合, ホイールオドメトリのみの場合とIMUありの場合の取り扱いについては本日決めましょう.

いいと思います。robot_localizationを使うか否かのパラメータを作ってあげて、defaultは使わない設定でmainにマージするのが良いかもしれません。

**Comment by Alpaca-zip** [comment]
結局のところrobot_localizationを使う想定でhttps://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2/pull/53 をマージしたのでこちらのissueは閉じます。また、[develop/not_to_use_robot_localization](https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2/tree/develop/not_to_use_robot_localization)も不要なため削除します。
